Add type overloads to methods
ollama/ollama-python pull request #181
Opened 2024-06-05 20:29 UTC by royjhan

In reference to #132

2024-06-06 21:10 UTC, mxyng requested changes

2024-06-06 21:10 UTC, mxyng commented on ollama/_client.py
> +    stream: bool = False,
This is incorrect since it creates an overlap between the two overloads

```suggestion
    stream: Literal[False] = False,
```

2024-06-06 21:10 UTC, mxyng commented on ollama/_client.py
> +    stream: bool = True,
```suggestion
    stream: Literal[True] = True,
```

2024-06-14 18:45 UTC, mxyng commented on ollama/_client.py
> +    stream: Literal[False] = False,
```suggestion
    stream: bool = False,
```

2024-06-18 20:21 UTC, mxyng commented on ollama/_client.py
> +  ) -> Mapping[str, Any]: ...
this is minor but it'd be better if `...` was on a newline. it's easier to read and harder to miss

2024-06-18 20:21 UTC, mxyng approved these changes

2024-06-19 22:32 UTC, royjhan commented
poetry doesn't let me move the ellipsis to a new line, lmk and I can just revert and merge

2024-06-19 22:54 UTC, mxyng commented
> poetry doesn't let me move the ellipsis to a new line, lmk and I can just revert and merge

ok let's go with the previous, inline style :(

2024-06-19 23:10 UTC, merged